name: http/X flavors CI

on:
  push:
    tags:
      - v**
      - latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: X flavor
      uses: docker/build-push-action@v4.0.0
      with:
        file: Dockerfile.X
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/grm:X-${{ github.ref_name }}
        push: true
        
    - name: http flavor
      uses: docker/build-push-action@v4.0.0
      with:
        file: Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/grm:http-${{ github.ref_name }}
        push: true
