name: http/X flavors CI

on:
  push:
    tags:
      - v*
      - latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: X flavor
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile.X
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/grm:X-${{ github.ref_name }}
        push: true
        
    - name: http flavor
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/grm:http-${{ github.ref_name }}
        push: true
