name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      #if: github.ref_type == 'tag'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      #if: github.ref_type == 'tag'
        
    - name: Build & Push Docker http flavor
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile
        tags: grm:http-${{ github.ref_name }}
      #if: github.ref_type == 'tag'
      
    - name: Build & Push Docker X flavor
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile.X
        tags: grm:X-${{ github.ref_name }}
      if: github.ref_type == 'tag'
